key STRING NOT NULL,
ts BIGINT NOT NULL,
level STRING NOT NULL,
severity INT,
double_field DOUBLE NOT NULL,
float_field FLOAT NOT NULL,
int_field INT NOT NULL,
long_field BIGINT NOT NULL,
boolean_field BOOLEAN NOT NULL,
string_field STRING NOT NULL,
bytes_field BINARY NOT NULL,
decimal_field DECIMAL(20,2) NOT NULL,
nested_record STRUCT<nested_int: INT, level: STRING>,
nullable_map_field MAP<STRING, STRUCT<nested_int: INT, level: STRING>>,
array_field ARRAY<STRUCT<nested_int: INT, level: STRING>> NOT NULL,
enum_field STRING NOT NULL,
date_nullable_field DATE,
timestamp_millis_nullable_field TIMESTAMP,
timestamp_micros_nullable_field TIMESTAMP,
timestamp_local_millis_nullable_field TIMESTAMP,
timestamp_local_micros_nullable_field TIMESTAMP,
payload VARIANT NOT NULL,
variant_in_struct STRUCT<v: VARIANT, i: INT>,
variant_in_array ARRAY<VARIANT>,
variant_in_map MAP<STRING, VARIANT>
